openapi: 3.0.1
info:
  title: bootcamp_turma01_api_netcore
  description: API - bootcamp_turma01_api_netcore
  version: v1
servers:
  - url: /bootcamp_turma01_api_netcore
paths:
  '/clientes/{id}':
    get:
      tags:
        - Cliente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ClienteModel'
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ClienteModel'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '500':
          description: Server Error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
  /clientes:
    get:
      tags:
        - Cliente
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClienteModel'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClienteModel'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClienteModel'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '500':
          description: Server Error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
    post:
      tags:
        - Cliente
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClienteModel'
          text/json:
            schema:
              $ref: '#/components/schemas/ClienteModel'
          'application/*+json':
            schema:
              $ref: '#/components/schemas/ClienteModel'
      responses:
        '201':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ClienteModel'
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ClienteModel'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '500':
          description: Server Error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
components:
  schemas:
    ClienteModel:
      type: object
      properties:
        id:
          type: string
          format: uuid
        nome:
          type: string
          nullable: true
        sobrenome:
          type: string
          nullable: true
        cpf:
          type: string
          nullable: true
        ddd:
          type: integer
          format: int32
          nullable: true
        telefone:
          type: string
          nullable: true
        email:
          type: string
          nullable: true
        segmento:
          type: string
          nullable: true
      additionalProperties: false
    ErrorModel:
      type: object
      properties:
        erros:
          type: array
          items:
            type: string
          nullable: true
          readOnly: true
      additionalProperties: false
